RECEIVER_EMAIL = "<RECEIVER_EMAIL>"
CC_EMAILS = "<CC_EMAIL_1>; <CC_EMAIL_2>"
SUBJECT = "<EMAIL SUBJECT>"
MESSAGE = "<EMAIL BODY>"

ATTACHMENT_1 = "<ATTACHMENT_1>"
ATTACHMENT_2 = "<ATTACHMENT_2>"
ATTACHMENT_3 = "<ATTACHMENT_3>"
